[workspace]
resolver = "2"
members = [
    "firmware",
    "m1284p-firmware",
    "stm32f4-firmware",
]

[profile.dev]
panic = "abort"
lto = true
opt-level = "z"

[profile.release]
panic = "abort"
codegen-units = 1
debug = false
lto = true
opt-level = "z"
